use serde::{Deserialize, Serialize};

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MathStateMachineApiSchema {
    Add,
    Sub,
    Mul,
    Div,
    Mod,
    Abs,
    Min,
    Max,
    Clamp,
    Floor,
    Ceil,
    Round,
    Trunc,
    Sign,
    Sqrt,
    Pow,
    Sin,
    Cos,
    Tan,
    Asin,
    Acos,
    Atan,
    Atan2,
    Lerp,
    MatrixComposeTrs,
    MatrixDecomposeTrs,
    MatrixInverse,
    MatrixMultiply,
    MatrixTranspose,
    QuaternionFromTo,
    QuaternionLookRotation,
    QuaternionMultiply,
    QuaternionNormalize,
    QuaternionSlerp,
    TransformDirection,
    TransformPoint,
    TransformVector,
}